In [46]:
import pandas as pd
import numpy as np
import os

data_filtered = pd.read_csv('data_100Entry.csv')


Filtered_Keyword = pd.read_csv('/Users/zhongxur/Downloads/599 Project - Sheet1.csv')


df = data_filtered


cancer_key = Filtered_Keyword['cancer']
pregnancy_key = Filtered_Keyword['pregnancy']
alcohol_key = Filtered_Keyword['alcohol']

df['Topic_category_C'] = df['Query'].apply(lambda x:1 if any([k in str(x) for k in cancer_key]) else 0)
df['Topic_category_P'] = df['Query'].apply(lambda x:1 if any([k in str(x) for k in pregnancy_key[:7]]) else 0)
df['Topic_category_A'] = df['Query'].apply(lambda x:1 if any([k in str(x) for k in alcohol_key[:7]]) else 0)


mask = (df['Topic_category_C']== 1) | (df['Topic_category_P']== 1) | (df['Topic_category_A']== 1)

df_category_filtered = df[mask]

df_category_filtered.to_csv('data_topic_filted.csv')

In [47]:
df_category_filtered

,Unnamed: 0,AnonID,Query,QueryTime,ItemRank,ClickURL,Topic_category_C,Topic_category_P,Topic_category_A
74,285,2178,lily pads breast,2006-04-29 14:52:29,NaN,NaN,1,0,0
82,293,2178,foods to avoid when pregnant,2006-05-09 19:32:42,4,http://www.americanpregnancy.org,0,1,0
83,294,2178,foods to avoid when breast feeding,2006-05-09 19:36:44,1,http://www.lalecheleague.org,1,0,0
84,295,2178,foods to avoid when breast feeding,2006-05-09 19:36:44,4,http://www.babycenter.com,1,0,0
99,310,2178,babycenter.com,2006-05-12 17:43:59,1,http://www.babycenter.com,0,1,0
...,...,...,...,...,...,...,...,...,...
23926310,3608726,24499604,baby superstore,2006-05-28 12:50:33,NaN,NaN,0,1,0
23926311,3608727,24499604,baby superstore houston tx,2006-05-28 12:54:46,1,http://www.hellohouston.com,0,1,0
23926312,3608728,24499604,shop baby superstore houston tx,2006-05-28 12:57:39,NaN,NaN,0,1,0
23926315,3608731,24499604,shop baby superstore houston tx,2006-05-28 13:24:27,NaN,NaN,0,1,0
23926407,3609295,24527055,babyphat,2006-05-28 02:19:11,NaN,NaN,0,1,0